#!/usr/bin/env bash

source $1
curr_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
heads_dir=${heads_dir:-$curr_dir/../data/heads}
logs_dir=${logs_dir:-$curr_dir/../data/logs}
repo_info_dir=${repo_info_dir:-$curr_dir/../data/repo}

cd $repo_dir
git fetch $prod_remote $prod_branch

for remote in `git remote`; do
    [[ $remote == $prod_remote ]] && continue
    git fetch $remote
    remotes+='{ "name": "'$remote'" }, '

    # Get the remote's branch
    branch=$(git remote show $remote | grep -P "^\s*HEAD branch:" | sed s'/\s*HEAD branch: //')
    echo "{ \"branch\": \"$branch\" }" > $heads_dir/$remote.json

    # Get the differences between the remote's head and production
    head=$(git ls-remote $remote HEAD | grep -P '\tHEAD$' | sed s'/\t.*//')
    $curr_dir/git-json-log $head ^$prod_remote/$prod_branch > $logs_dir/$remote.json
done

echo '['${remotes:0:-2}']' > $repo_info_dir/remotes.json
