#!/usr/bin/env bash

source $1
curr_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
data_dir=${data_dir:-$curr_dir/../data}

cd $repo_dir
git fetch $prod_repo $prod_branch

for repo in `git remote`; do
    [[ $repo == $prod_repo ]] && continue
    git fetch $repo

    # Get the remote's branch
    branch=$(git remote show $repo | grep -P "^\s*HEAD branch:" | sed s'/\s*HEAD branch: //')
    repos+='{ "name": "'$repo'" , "head": "'$branch'" }, '

    # Get the differences between the remote's head and production
    head=$(git ls-remote $repo HEAD | grep -P '\tHEAD$' | sed s'/\t.*//')
    $curr_dir/git-json-log $head ^$prod_repo/$prod_branch > $data_dir/commits_$repo.json

    # Create info file for the repository
    if [[ ! -f $data_dir/info_$repo.json ]]; then
        echo '{ "notes": "" }' > $data_dir/info_$repo.json
    fi
done

echo "[$repos]" | sed 's/, \]/\]/' > $data_dir/repos.json
